### PR TITLE
Update the selected publications according to Bob's suggestions

### PR DESCRIPTION
**Pull request by boldar99**
Bob's email according to which the changes have been made:

Had a look at the ZX-page and in the light how broad the popularity is becoming among potentially interested young researchers, people at business/evangelise side etc it is a little outdated on some fronts, and not entirely inclusive.  It shows up first in any search for ZX, even before the wiki, so needs some improving.

The most outdated would be the example papers, which may scare more people away than attract, as none of them really can be called a `taster’.  John’s tutorial is really for someone who actively wants to use ZX at the cutting-edge of quantum computing, and in the dodo book you need to swallow 500 pages before getting at ZX.  I suggest the following structure in order to augment inclusivity: 

1) Have a taste of ZX-calculus:

- Basic ZX-calculus: the shortest path if you know some Dirac notation

- Kindergarten QM graduates: a glimpse of some recent practical developments

- John’s: tutorial on ZX at the cutting-edge of QC

2) Books on ZX-calculus:

- QiP: no math prerequisites whatsoever

- PQP: the bible of (quantum) diagrammatic reasoning

- Chris/Jamie: all in terms of category theory

https://zxcalculus.com/intro.html is ok but shouldn’t be called an introduction as it doesn’t even list hopf or anything.  It’s more like “trailer”.

Regarding the two other listed papers, there are now so many applications that only listing circuit optimisation is too inward looking.  Such example technical papers should include at least one team that are not “us”, e.g. the latest PsiQuantum paper and Shor's paper.    

Only listing Renaud for completeness also isn’t fair on others.  If anything is mentioned on completeness you’d expect a paragraph first explaining in simple terms what it is, as a slogan or so: “ZX-can produce any equation that you can obtain in Hilbert space”, and then maybe Miriam, Amar-Harny-KF, and then Renaud.

### CODE REVIEW

**Review by hmillerbakewell — COMMENTED** [review]
# Titles

I'm not a fan - the examples higher up on that page are a taste of the ZX calculus, and those publications are often a lot more than a taste. I like it being split between "papers" and "books" though. Perhaps "Surveys and Introductions" and "Books"?

# Formatting

I like the proposed change of dropping years and adding colons. I would prefer to see the colons outside of the `<a>` tags.

# Papers

2303.03163: Not this one - we could maybe link to a recording if there is one, but between the formatting, content, and tone I don't think this is a good candidate for this section. Revert this back to 2012.13966

2102.10984: Keep

1812.09114: Put this one back in - we need a (easy to find) link somewhere on the site to a complete ruleset for those that want to dive in, and I think this is the best place for it.

# Books

QiP: Keep, but make it `maths` (plural) because the site is in British English.

PQP: I disagree with the characterisation of PQP as a bible (it's a good first course, but it's not an essential tool for practitioners). Use the part of the title that comes after the colon as the strapline.

CfQT: This strapline doesn't add anything. Perhaps `the category theory that underpins ZX`?

# Pull Request

In future add comments to your request explaining your reasoning. If you make formatting and style changes (as you have done here) those should also be acknowledged in your pull request.

**Comment by boldar99** [comment]
@hmillerbakewell, I have just updated the descrpition of the PR with Bob's email where his reasoning can be found.

I agree with you regarding formatting and books.
Though I see Bob's thinking as well calling it a bible. I can have another round with him to discuss this!

Regarding the papers, I personally like Bob's suggestions based on his reasoning.
It's definitely a good idea to include the recording if it's public!

**Comment by akissinger** [comment]
I agree with the spirit of the update, in making things be less inward looking and accounting for things that have recently come out. I don't really agree with the selection of papers though. In particular, I think "ZX-calculus for the working quantum computer scientist" should remain top of the list as a good starting point for someone quantum-literate and not be essentially replaced by "basic ZX" in this role, and more generally the proposed list is very Bob-heavy and could reflect the larger community better.

**Comment by jvdwetering** [comment]
Agree with Aleks: updating the listed papers/books is a good idea, but I don't agree with the current suggested ones.
I don't want to toot my own horn too much, but when people join in the ZX Discord and they say how they are learning ZX, it is through my review; I haven't really heard anyone say 'this is too hard, is there an easier introduction?', so I would be inclined to just keep it at the top of the list. Definitely QiP should be added to the list as something more accessible though.

I also don't like the phrasing of PQP being 'the Bible'. Maybe something like 'PQP: for when you want to learn quantum theory from the ground up using diagrams'?

I agree that the current list of papers is too selective and inward looking. Maybe we can have a list where for every application area we have a good introduction paper? So something for completeness, optimisation, MBQC, NLP, surface codes / lattice surgery, other stuff?

**Comment by hmillerbakewell** [comment]
I like the idea of an introduction / survey paper per research area.

For PQP the subtitle on the book itself is "A First Course in Quantum Theory and Diagrammatic Reasoning" and I think that's a really good description and advert for the book. I realise I am out of date, but I also think John's review should stay at the top.
The list of topics and papers might be something to discuss further in the #outreach Discord channel.

**Pull request closed without merging**
